version: "3.3"
services:
  app_vidaloestodo_prod:
    build:
      args:
        user: eurodocker
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: vidaloestodo
    container_name: app_vidaloestodo_prod
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - network-prod

  db_vidaloestodo_prod:
    image: mysql:8.0
    container_name: db_vidaloestodo_prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 3307:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/mysql
    networks:
      - network-prod

  nginx_vidaloestodo_prod:
    image: nginx:alpine
    container_name: nginx_vidaloestodo_prod
    restart: unless-stopped
    ports:
      # - "127.0.0.1:8000:80"
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d/
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - network-prod
    depends_on:
      - app_vidaloestodo_prod

networks:
  network-prod:
    driver: bridge